name: $(Build.SourceBranch)

trigger:
  branches:
   include:
   - release/*
   - development
  tags: 
   include:
   - v*

variables:
  buildVariant: 'assemble'
  ${{ if eq(variables['build.SourceBranch'], 'refs/heads/release/1.0.0') }}:
    buildVariant: 'assembleUatDebug'
  ${{ if eq(variables['build.SourceBranch'], 'refs/heads/develop') }}:
    buildVariant: 'assembleDevDebug'

pool:
  vmImage: 'macos-latest'

stages:
  - stage: BuildNumberGenerator  
    displayName: Build Version Tag
    jobs:
    - job: GenerateReleaseVersionTag
      condition: or(startsWith(variables['build.sourceBranch'], 'refs/heads/development'), startsWith(variables['build.sourceBranch'], 'refs/heads/release/'))
      variables: 
        revision: $[counter(variables['build.sourcebranchname'], 0)]
      steps:
      - bash: echo '##vso[build.updatebuildnumber]r$(build.sourcebranchname)-$(revision)'

    - job: GenerateMasterVersionTag
      condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
      variables: 
        revision: $[counter(variables['build.sourceBranch'], 0)]
      steps:
      - bash: echo '##vso[build.updatebuildnumber]v$(build.sourcebranchname)-$(revision)'

  - stage: BuildSteps
    jobs:
    - job: Build 
      condition: or(or(startsWith(variables['build.sourceBranch'], 'refs/heads/development'), startsWith(variables['build.sourceBranch'], 'refs/heads/release/')), startsWith(variables['build.sourceBranch'], 'refs/tags/'))
      steps:
      - checkout: self
        path: s/onekey-sdk-android-lib

      - task: DownloadSecureFile@1
        name: privateKeyring
        displayName: 'Download private keyring'
        inputs:
          secureFile: 'secring.gpg'

      - script: | 
          echo Moving $(privateKeyring.secureFilePath) to the project.
          mv $(privateKeyring.secureFilePath) s/onekey-sdk-android-lib/healthcarelocator

      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          tasks: healthcarelocator:assemble

      - task: PublishPipelineArtifact@1
        inputs:
          artifactName: 'code'
          path: s/onekey-sdk-android-lib